### ISSUE TITLE
Error: Cannot find module '../src/cli/main'

### ISSUE THREAD

**Issue by felixfbecker** [JoshuaKGoldberg/tslint-to-eslint-config#93]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 0.1.8
-   ESLint version: n/a
-   Node version: 11.15.0

#### Actual Behavior

```
> tslint-to-eslint-config --tslint ../tslint-config/tslint.json
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module '../src/cli/main'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/local/share/powershell/Modules/nvm/2.3.0/vs/v11.15.0/lib/node_modules/tslint-to-eslint-config/bin/tslint-to-eslint-config:3:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
```

#### Expected Behavior

no error

#### Reproduction

`tslint-to-eslint-config --version`

**Comment by JoshuaKGoldberg** [comment]
Thanks _(again)_ for the bug report @felixfbecker! Looks like `tsc` output wasn't preserved in the `publish` task? Either that, or I slipped up doing a local publish. Interesting.

In the meantime I published v0.1.19 that works locally.
